[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
HaltonSequences = "13907d55-377f-55d6-a9d6-25ac19e11b95"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RadialBasisFunctions = "79ee0514-adf7-4479-8807-6f72ea8967e8"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[compat]
BenchmarkTools = "1.5"
RadialBasisFunctions = "0.3"
julia = "1.9"
