name = "RadialBasisFunctions"
uuid = "79ee0514-adf7-4479-8807-6f72ea8967e8"
version = "0.3.0"
authors = ["Kyle Beggs"]

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
SymRCM = "286e6d88-80af-4590-acc9-0001b223b9bd"

[weakdeps]
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
RadialBasisFunctionsChainRulesCoreExt = "ChainRulesCore"
RadialBasisFunctionsMooncakeExt = ["ChainRulesCore", "Mooncake"]

[compat]
ChainRulesCore = "1.20"
ChunkSplitters = "3"
Combinatorics = "1"
Distances = "0.9, 0.10"
FiniteDifferences = "0.12.33"
KernelAbstractions = "0.9.34"
LinearAlgebra = "1"
Mooncake = "0.4"
NearestNeighbors = "0.4.8"
PrecompileTools = "1.2"
StaticArrays = "1.9.15"
StaticArraysCore = "1.4"
SymRCM = "0.2"
julia = "1.10"
